name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ficflow
            asset_name: ficflow-linux-amd64
          - os: windows-latest
            artifact_name: ficflow.exe
            asset_name: ficflow-windows-amd64.exe
          - os: macos-latest
            artifact_name: ficflow
            asset_name: ficflow-macos-amd64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Sync Cargo.toml version with tag
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Setting Cargo.toml version to $VERSION"
          python -c "
          import re
          src = open('Cargo.toml').read()
          new = re.sub(r'^version\s*=\s*\"[^\"]*\"', f'version = \"$VERSION\"', src, count=1, flags=re.M)
          open('Cargo.toml', 'w').write(new)
          "
          grep '^version' Cargo.toml

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true